# GET /email/sent
get:
  summary: List all sent emails
  operationId: listSentEmails
  tags:
    - email
  parameters:
    - name: userEmail
      in: query
      schema:
        type: string
      description: The email address of the user to get sent emails to or from
  responses:
    "200":
      description: A list of sent emails.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../schemas/sent-email.yaml"
    "403":
      description: Forbidden - server is not mocking email sends
      content:
        application/json:
          schema:
            $ref: "../schemas/error.yaml"
