openapi: 3.0.0
info:
  title: Secrets API
  version: 1.0.0
  description: API specification for template-service service

paths:
  /secrets:
    get:
      $ref: "./routes/secrets/list.yaml#/listSecrets"
    post:
      $ref: "./routes/secrets/create.yaml#/createSecret"
  /secrets/{id}:
    put:
      $ref: "./routes/secrets/update.yaml#/updateSecret"
    delete:
      $ref: "./routes/secrets/delete.yaml#/deleteSecret"
  /access-requests:
    get:
      $ref: "./routes/access-requests/list.yaml#/listAccessRequests"
  /access-requests/{id}/approve:
    post:
      $ref: "./routes/access-requests/approve.yaml#/approveAccessRequest"
  /service-tokens:
    get:
      $ref: "./routes/service-tokens/list.yaml#/listServiceTokens"
  /service-tokens/{id}/approve:
    post:
      $ref: "./routes/service-tokens/approve.yaml#/approveServiceToken"

components:
  schemas:
    # Add your shared schemas here
    Error:
      $ref: "./schemas/error.yaml"
    Secret:
      $ref: "./schemas/secret.yaml"
    SecretCreateRequest:
      $ref: "./schemas/secret-create-request.yaml"
    SecretUpdateRequest:
      $ref: "./schemas/secret-update-request.yaml"
    ServiceToken:
      $ref: "./schemas/service-token.yaml"
    AccessRequest:
      $ref: "./schemas/access-request.yaml"
    ApprovalRequest:
      $ref: "./schemas/approval-request.yaml"
