# common elements between dev and test
services:
  clients:
    ports:
      - 5173:5173
    build:
      context: ../..
      dockerfile: ./secrets/secrets-sdk/Dockerfile
    command: npm run dev
    volumes:
      - ./:/app/secrets/secrets-sdk/
