openapi: 3.0.0
info:
  title: SAF Auth API
  version: 1.0.0
  description: Authentication API for SAF

paths:
  /auth/register:
    post:
      $ref: "./routes/register-user.yaml#/registerUser"
  /auth/login:
    post:
      $ref: "./routes/login-user.yaml#/loginUser"
  /auth/logout:
    post:
      $ref: "./routes/logout-user.yaml#/logoutUser"
  /auth/verify:
    get:
      $ref: "./routes/verify-auth.yaml#/verifyAuth"
  /auth/forgot-password:
    post:
      $ref: "./routes/forgot-password.yaml#/forgotPassword"
  /auth/reset-password:
    post:
      $ref: "./routes/reset-password.yaml#/resetPassword"
  /auth/verify-email:
    $ref: "./routes/auth.yaml#/verify-email"
  /auth/resend-verification:
    $ref: "./routes/auth.yaml#/resend-verification"
  /auth/set-password:
    $ref: "./routes/auth.yaml#/set-password"
  /auth/profile:
    get:
      $ref: "./routes/profile.yaml#/get"
    put:
      $ref: "./routes/profile.yaml#/put"
  /users:
    get:
      $ref: "./routes/users.yaml#/list"
  /auth/email/sent:
    get:
      $ref: "../email-spec/routes/email_routes.yaml#/get"

components:
  securitySchemes:
    scopes:
      type: apiKey
      in: header
      name: X-User-Scopes
      description: Comma-separated list of user scopes
  schemas:
    $ref: "./routes/auth.yaml#/components/schemas"
