openapi: 3.0.0
info:
  title: SAF Auth API
  version: 1.0.0
  description: Authentication API for SAF

paths:
  /auth/register:
    $ref: "./routes/auth.yaml#/register"
  /auth/login:
    $ref: "./routes/auth.yaml#/login"
  /auth/logout:
    $ref: "./routes/auth.yaml#/logout"
  /auth/verify:
    $ref: "./routes/auth.yaml#/verify"
  /auth/forgot-password:
    $ref: "./routes/auth.yaml#/forgot-password"
  /auth/reset-password:
    $ref: "./routes/auth.yaml#/reset-password"
  /auth/verify-email:
    $ref: "./routes/auth.yaml#/verify-email"
  /auth/resend-verification:
    $ref: "./routes/auth.yaml#/resend-verification"
  /auth/set-password:
    $ref: "./routes/auth.yaml#/set-password"
  /auth/profile:
    get:
      $ref: "./routes/profile.yaml#/get"
    put:
      $ref: "./routes/profile.yaml#/put"
  /users:
    get:
      $ref: "./routes/users.yaml#/list"

components:
  securitySchemes:
    scopes:
      type: apiKey
      in: header
      name: X-User-Scopes
      description: Comma-separated list of user scopes
  schemas:
    $ref: "./routes/auth.yaml#/components/schemas"
